image: gcc

stages:
  - build
  - test

build:
  stage: build
  script:
    - mkdir build && cd build
    - cmake ..
    - cmake --buid .
  artifacts:
    expire_in: 10 mins
    paths:
      - build/*

test:
  stage: test
  script:
    - cd build
    - ctest .