image: gcc

stages:
  - build
  - test

build:
  stage: build
  script:
    - apt-get update && apt-get install -y cmake && apt-get update
    - mkdir build && cd build
    - cmake ..
    - cmake --build .
  artifacts:
    expire_in: 10 mins
    paths:
      - build/*

test:
  stage: test
  script:
    - cd build
    - ctest .
