language: cpp


matrix:
  include:
    - os: linux
      dist: bionic
      sudo: true
      compiler: gcc
      addons:
        apt:
          packages:
            lcov
          sources:
            - ubuntu-toochain-r-test

  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --buid .
    - ctest